### ISSUE TITLE
document is undefined on Universal Apps

### ISSUE THREAD

**Issue by johndugan** [LinusBorg/vue-simple-portal#21]
Hi Linus,

I'm working on a universal nuxt application. I'm getting a reference error "document is not defined". Looks like you may need an `isBrowser` check on the `mount` method. Below resolved the error for me. Of course, the portal markup doesn't then render server side.

```
mount: function mount() {
    if (!isBrowser) return;
    var targetEl = this.getTargetEl();
    var el = document.createElement('DIV');
    ...
```

**Comment by callumacrae** [comment]
My workaround until this is merged is to just add a `v-if="isBrowser"` to the portal component:

```
<portal v-if="isBrowser">
```

and then just define `isBrowser` in the data object.
