### ISSUE TITLE
Bug with render \ destroy component ?

### ISSUE THREAD

**Issue by EgorFront** [LinusBorg/vue-simple-portal#42]
I get an error
"Error in destroyed hook:" TypeError: cannot read the 'removeChild' property from null"

I did a [demo here](https://codesandbox.io/s/interesting-hoover-bjxiq?file=/src/main.js)

### Step to reproduce
1. Go to Home page
2. Open Modal
3. Click link inside modal to go to other route

There 2 problems. Error in console and no removal of the modal window

### Workaround
I found workaround, which is add `v-if` to `modal-portal` component, like this
```vue
<modal-portal v-if="modalActive">
      <modal-wrapper @close="modalActive = false" :active="modalActive">
         <div></div>
      </modal-wrapper>
</modal-portal>
```
But I didnt find anything about this in docs or caveats

### Possible solution
1. Add info about this problem to docs or caveats
2. I will do a PR with a solution that I think solves the problem

**Comment by LinusBorg** [comment]
this should be resolved in 0.1.5
