### ISSUE TITLE
Portal component name

### ISSUE THREAD

**Issue by tmorehouse** [LinusBorg/vue-simple-portal#8]
Should this use `PortalSimple` instead of `Portal` to prevent conflicts if using both `portal-vue` and `vue-simple-portal`?  Although I know one can import Portal as an alias.

**Comment by tmorehouse** [comment]
Ah, I just noticed that the name can be changed in the config options.

**Comment by LinusBorg** [comment]
Yep. That should solve it. 

Also using both libs in a project seems unnecessary.
